'use client';
import type { Metadata } from 'next';
import './globals.css';

const metadata: Metadata = {
  title: 'TrackerX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="../"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className="overflow-auto">{children}</body>
    </html>
  );
}
