'use client';
import type { Metadata } from 'next';
import { RecoilRoot } from 'recoil';
import BottomNav from './components/bottomnav';
import NavBar from './components/sidebarnav';
import TopNav from './components/topnav';

const metadata: Metadata = {
  title: 'TrackerX',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilRoot>
      <html lang="en">
        <head>
          <link
            rel="icon"
            href="../"
            type="image/<generated>"
            sizes="<generated>"
          />
        </head>
        <body className="overflow-auto">
          {' '}
          {/* Add overflow-hidden to prevent body scrolling */}
          {/* <div className="flex flex-col h-screen"> */}
          <div className="h-screen flex flex-col lg:flex lg:flex-row-reverse">
            {/* Header */}

            <header>
              {' '}
              {/* Add fixed header styling */}
              <div className="hidden md:hidden lg:block">
                <NavBar />
              </div>
              <div className="block lg:hidden w-full">
                <TopNav />
              </div>
            </header>

            {/* Main Content */}
            <div className="flex-1 overflow-auto">
              <main className="h-full w-full overflow-auto">{children}</main>
            </div>

            {/* Footer */}
            <footer className="lg:hidden">
              {' '}
              {/* Add fixed footer styling */}
              <BottomNav />
            </footer>
          </div>
        </body>
      </html>
    </RecoilRoot>
  );
}
